### ISSUE TITLE
Generalize handling of atmospheric field names in derived quantities

### ISSUE THREAD

**Issue by jpdunc23** [ai2cm/ace#181]
I see three options:

1. Add some sort of config parameter for specifying which `in_names` match which standard names used for derived quantities. Here's an experimental PR which takes that approach: https://github.com/ai2cm/full-model/pull/261
2. Map `in_names` to some set of standardized names, e.g. change `in_names` to a dictionary along the lines of:
```
# train-config.yaml
...
stepper:
  ...
  in_names:
    PS: surface_pressure
    FLUT: toa_upward_longwave_flux
```
3. Handle the mapping `CLIMATE_FIELD_NAME_PREFIXES` in dataclasses like `FV3GFSData` and `E3SMV2Data`. The former is currently only used for testing and the latter doesn't exist yet. But I think it makes sense to have a climate dataset typing abstraction for each new dataset that we add (e.g., could also have `ERA5Data`), and maybe each of these could inherit from `ClimateData`.

I personally think option 3 is nicest.
