### ISSUE TITLE
Add an option to restrict the training data in order to create a heldout dataset.

### ISSUE THREAD

**Issue by gideonite** [ai2cm/ace#274]
I think the simplest thing from the user standpoint would be to add a field to `train_loader.dataset`. This option would only work is data type is ensemble, and otherwise (e.g. for xarray datatype), would throw an error when the config classes are initialized before training begins.

```
train_loader:
  batch_size: 4
  data_type: ensemble_xarray
  num_data_workers: 8
  dataset:
    data_path: /traindata
    heldout_ic: ic_0001  # ← NEW
```

**Comment by oliverwm1** [comment]
I would generalize the naming of the option—this could be used for all sorts of reasons, e.g. doing an ablation on dataset size. Also the ensemble dataset doesn't know anything about the "name" of each sub-path, just that there is a certain number of them.

So I'd suggest something like
```
train_loader:
  batch_size: 4
  data_type: ensemble_xarray
  num_data_workers: 8
  ensemble_size: 9   # the "_get_ensemble_dataset" function would take this and shorten the "paths" list accordingly. If not provided, use all ensemble members.
  dataset:
    data_path: /traindata
```

If we need more fine-grained control (I'm not convinced we do) we could also specify the particular ensemble members to use.
