### ISSUE TITLE
Allow override of dataset variables by ordering merged datasets

### ISSUE THREAD

**Issue by mcgibbon** [ai2cm/ace#601]
See discussion in PR looking at allowing later datasets to override previous datasets when merging: https://github.com/ai2cm/full-model/pull/1816

> Based on discussion this morning, possible options:
> 
> 1. proceed with this PR, with awareness of possible confusing behavior if order of mapping changes in serialized yaml.
> 2. switch the "merge dataset" feature to be configured as another sequence (instead of mapping) so that the importance of its order is clearer and so that the order can't change during serialization.
> 3. stop allowing the merge of arbitrary # of datasets, and instead have a single required base dataset and a single optional override dataset.
> 
> I think we should avoid adding the complexity of manually configuring some kind of priority on a per-dataset level.

We would like to be able to support more than 2 datasets based on discussion in Slack.

Another idea came up in slack discussion to make use of Sequence for the merged type also. This could look like:

```
validation_loader:
  batch_size: 128
  num_data_workers: 32
  dataset:
    - - data_path: /some-atmosphere-data
        subset:
          start_time: '1998-01-01'
          stop_time: '2000-12-31'
      - data_path: /some-atmosphere-data
        subset:
          start_time: '1996-01-01'
          stop_time: '1997-12-31'
    - - data_path: /dataset-with-missing-variable
        subset:
          start_time: '1998-01-01'
          stop_time: '2000-12-31'
      - data_path: /dataset-with-missing-variable
        subset:
          start_time: '1996-01-01'
          stop_time: '1997-12-31'
```

Another potential solution is to have a `exclude_names` key on XarrayDatasetConfig, but this doesn't have much purpose when not being used within merged datasets.

A related issue brought up was that we are using the `if isinstance`-chain anti-pattern for merged/concat implementations of "methods":
```
    if isinstance(config.dataset, Sequence):
        dataset, properties = get_dataset(
            config.dataset,
            requirements.names,
            requirements.n_timesteps,
            strict=config.strict_ensemble,
        )
    elif isinstance(config.dataset, Mapping):
        dataset, properties = get_merged_datasets(
            config.dataset,
            requirements.names,
            requirements.n_timesteps,
            strict=config.strict_ensemble,
        )
```

If we used a change in the data loader config like

```
    dataset: Union[Sequence[XarrayDataConfig], Mapping[str, Sequence[XarrayDataConfig]]]
```
to
```
    dataset: Union[ConcatDatasetConfig, MergedDatasetConfig]
```

With something like

```
class ConcatDatasetConfig:
    concat_datasets: List[XarrayDatasetConfig]

class MergedDatasetConfig:
    merged_datasets: List[ConcatDatasetConfig]
```

we could instead implement these as methods of concrete types. This has would look like:

```
validation_loader:
  batch_size: 128
  num_data_workers: 32
  dataset:
    merged_datasets:
      - concat_datasets:
        - data_path: /some-atmosphere-data
          subset:
            start_time: '1998-01-01'
            stop_time: '2000-12-31'
        - data_path: /some-atmosphere-data
          subset:
            start_time: '1996-01-01'
            stop_time: '1997-12-31'
      - concat_datasets:
        - data_path: /dataset-with-missing-variable
          subset:
            start_time: '1998-01-01'
          stop_time: '2000-12-31'
        - data_path: /dataset-with-missing-variable
          subset:
            start_time: '1996-01-01'
            stop_time: '1997-12-31'
```

We could also consider allowing
```
dataset: Union[ConcatDatasetConfig, MergedDatasetConfig, XarrayDatasetConfig]
```

instead of using a length-1 concat dataset in the single-dataset case.

**Comment by oliverwm1** [comment]
I like
```
dataset: Union[ConcatDatasetConfig, MergedDatasetConfig, XarrayDataConfig]
```
but would slightly change the Concat/Merge configs to:
```
class ConcatDatasetConfig:
    concat: List[XarrayDataConfig]

class MergeDatasetConfig:
    merge: List[Union[ConcatDatasetConfig, XarrayDataConfig]]
```
dropping the `_datasets` from the keys to remove the "dataset" duplication in yaml. And slight preference for verb "merge" instead of "merged". And if we allow single `XarrayDataConfig` in top-level we should probably also allow it within `MergeDatasetConfig`.

So we end up with:
```
  batch_size: 128
  num_data_workers: 32
  dataset:
    merge:
      - concat:
        - data_path: /some-atmosphere-data
          subset:
            start_time: '1998-01-01'
            stop_time: '2000-12-31'
        - data_path: /some-atmosphere-data
          subset:
            start_time: '1996-01-01'
            stop_time: '1997-12-31'
      - concat:
        - data_path: /dataset-with-missing-variable
          subset:
            start_time: '1998-01-01'
          stop_time: '2000-12-31'
        - data_path: /dataset-with-missing-variable
          subset:
            start_time: '1996-01-01'
            stop_time: '1997-12-31'
```
