### ISSUE TITLE
Coupled dataset should conform to concat keyword

### ISSUE THREAD

**Issue by elynnwu** [ai2cm/ace#619]
In ai2cm/full-model#1877, `concat` is now a keyword used to indicate a list of datasets that should be concatenated. Coupled dataset should follow the same.

**Comment by mcgibbon** [comment]
@elynnwu could you clarify what class should have what feature added? e.g. does this mean a certain config class (which one?) should use a `concat:` object to contain a `list[DatasetConfig]` type, instead of having that `list` bare?

**Comment by elynnwu** [comment]
`CoupledDataLoaderConfig` accepts a sequence of `CoupledDatasetConfig`, which takes in atmosphere/ocean `XarrayDataConfig` that support concat within. To be completely consistent with the config style, we should probably just have  `CoupledDataLoaderConfig` accept `CoupledDatasetConfig` and not a sequence. @jpdunc23 can you think of a use case where we would want to have a list of `CoupledDatasetConfig` concatenated?

**Comment by jpdunc23** [comment]
> `CoupledDataLoaderConfig` accepts a sequence of `CoupledDatasetConfig`, which takes in atmosphere/ocean `XarrayDataConfig` that support concat within. To be completely consistent with the config style, we should probably just have `CoupledDataLoaderConfig` accept `CoupledDatasetConfig` and not a sequence. [@jpdunc23](https://github.com/jpdunc23) can you think of a use case where we would want to have a list of `CoupledDatasetConfig` concatenated?

> can you think of a use case where we would want to have a list of `CoupledDatasetConfig` concatenated?

Yes, I think this is currently the only way to use concatenation in `fme.coupled` since the components of `CoupledDatasetConfig` have type `XarrayDataConfig | MergeNoConcatDatasetConfig`. I think we want to keep this as is, i.e. in `fme.coupled` we concat coupled datasets, not the individual components datasets.

Are you proposing we change the `dataset` attribute of `CoupledDataLoaderConfig` from type `Sequence[CoupledDatasetConfig]` to something like `CoupledConcatDatasetConfig | CoupledDatasetConfig`? That would make sense.

**Comment by elynnwu** [comment]
Yes 

> from type Sequence[CoupledDatasetConfig] to something like CoupledConcatDatasetConfig | CoupledDatasetConfig

Our current coupled training pattern uses a single `CoupledDatasetConfig`:
```yaml
train_loader:
 ...
  dataset:
    - ocean:
        merge:
        - data_path: /climate-default
          file_pattern: <COUPLED_OCEAN_ZARR>
        - data_path: /climate-default
          file_pattern: <OCEAN_ZARR>
      atmosphere:
        merge:
        - data_path: /climate-default
          file_pattern: <COUPLED_ATMOS_ZARR>
        - data_path: /climate-default
          file_pattern: <ATMOS_ZARR>
```

Do we have a need to support something like `CoupledConcatDatasetConfig`?

**Comment by jpdunc23** [comment]
> Do we have a need to support something like CoupledConcatDatasetConfig?

We do need this feature, but we already support it via `dataset: Sequence[CoupledDatasetConfig]` with a config like:

```yaml
train_loader:
 ...
  dataset:
    - ocean:
        merge:
        - data_path: /climate-default
          file_pattern: <COUPLED_OCEAN_ZARR>
        - data_path: /climate-default
          file_pattern: <OCEAN_ZARR>
      atmosphere:
        merge:
        - data_path: /climate-default
          file_pattern: <COUPLED_ATMOS_ZARR>
        - data_path: /climate-default
          file_pattern: <ATMOS_ZARR>
    - ocean:
        merge:
        - data_path: /climate-default
          file_pattern: <ANOTHER_COUPLED_OCEAN_ZARR>
        - data_path: /climate-default
          file_pattern: <ANOTHER_OCEAN_ZARR>
      atmosphere:
        merge:
        - data_path: /climate-default
          file_pattern: <ANOTHER_COUPLED_ATMOS_ZARR>
        - data_path: /climate-default
          file_pattern: <ANOTHER_ATMOS_ZARR>
```

E.g., here's a [production coupled training run](https://beaker.org/orgs/ai2/workspaces/climate-titan/work/01KH2F952QKJWFN13EADZDEJZA?taskId=01KH2F95AV9PGGFWPMDH0B8CKH&jobId=01KH2F95F0NJ037X5V2R85JQKR) using concatenated CM4 piControl and 1pct.

Refactoring `dataset: Sequence[CoupledDatasetConfig]` to `dataset: CoupledConcatDatasetConfig | CoupledDatasetConfig` sounds good to me.

**Comment by elynnwu** [comment]
PR #818 addresses this, this is a breaking changes in the config though. Your example will become:
```yaml
train_loader:
 ...
  dataset:
    concat:
      - ocean:
          merge:
          - data_path: /climate-default
            file_pattern: <COUPLED_OCEAN_ZARR>
          - data_path: /climate-default
            file_pattern: <OCEAN_ZARR>
        atmosphere:
          merge:
          - data_path: /climate-default
            file_pattern: <COUPLED_ATMOS_ZARR>
          - data_path: /climate-default
            file_pattern: <ATMOS_ZARR>
      - ocean:
          merge:
          - data_path: /climate-default
            file_pattern: <ANOTHER_COUPLED_OCEAN_ZARR>
          - data_path: /climate-default
            file_pattern: <ANOTHER_OCEAN_ZARR>
        atmosphere:
          merge:
          - data_path: /climate-default
            file_pattern: <ANOTHER_COUPLED_ATMOS_ZARR>
          - data_path: /climate-default
            file_pattern: <ANOTHER_ATMOS_ZARR>
```

and the previous example using a single coupled dataset will need to remove the list:
```yaml
train_loader:
 ...
  dataset:
    ocean:
      merge:
      - data_path: /climate-default
        file_pattern: <COUPLED_OCEAN_ZARR>
      - data_path: /climate-default
        file_pattern: <OCEAN_ZARR>
    atmosphere:
      merge:
      - data_path: /climate-default
        file_pattern: <COUPLED_ATMOS_ZARR>
      - data_path: /climate-default
        file_pattern: <ATMOS_ZARR>
````
